### ISSUE TITLE
Drag interferes with pan on Angular 4.4.4

### ISSUE THREAD

**Issue by tom-s07** [lsharir/angular-d3-graph-example#1]
There seems to be an issue with the event propagation and some interference between node dragging and the svg panning when using your code with the current angular version (4.4.4).

Check this plunkr to see the problem:
http://plnkr.co/edit/6pd6gzC6ZndkrzLlJY3Y

Any idea how to address this issue?

**Comment by Jeslopov** [comment]
Hello Im having this same issue, I have seen that the problem have been fixed in this repo, but:
What was causing it??

**Comment by ju-tngh** [comment]
You have to add this line : 
  **d3.event.sourceEvent.stopPropagation();**
at the end of the "applyDraggableBehaviour -> function started" of the fil "d3.service.ts" and it should works :)
